# Generated by Django 5.0.2 on 2025-11-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_movil_escolar_api', '0003_alumnos_maestros'),
        ('web_movil_escolar_api', '0004_maestros_edad_alter_maestros_fecha_nacimiento_and_more'),
    ]

    operations = [
    ]
