# Generated by Django 4.2.7 on 2025-12-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_movil_escolar_api', '0006_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='programa_educativo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='materia',
            table=None,
        ),
    ]
